const generateCss = require('../../scripts/utils/generateCss');
const generateJson = require('../../scripts/utils/generateJson');
const extraFromJson = require('../../scripts/utils/extraFromJson');
const getIconsFromCss3 = require('../../scripts/utils/getIconsFromCss3');
const prepareIcons = require('../../scripts/utils/prepareIcons');
const getSvgs = require('../../scripts/utils/getSvgs');
const getSelectedSvgs = require('../../scripts/utils/getSelectedSvgs');
const copySvgs = require('../../scripts/utils/copySvgs');
const copyLicense = require('../../scripts/utils/copyLicense');
const generateFontsFromSvg = require('../../scripts/utils/generateFontsFromSvg');
const jsonfile = require('../../scripts/utils/jsonfile');
const clean = require('../../scripts/utils/clean');
const fs = require('fs-extra');
const path = require('path');

let options = {
  source: path.join(`${__dirname}/node_modules/`, 'simple-icons'),
  name: 'simple-icons',
  class: 'si',
  prefix: 'si-',
  className: 'SimpleIcons',
  title: 'Simple Icons',
  classifiable: false,
  selections: [
    'adobe',
    'adobeacrobatreader',
    'adobeaftereffects',
    'adobeillustrator',
    'adobeindesign',
    'adobelightroomcc',
    'adobephotoshop',
    'adobepremiere',
    'airbnb',
    'alipay',
    'amazon',
    'amd',
    'android',
    'angular',
    'apache',
    'apple',
    'applemusic',
    'applepay',
    'archlinux',
    'atom',
    'audi',
    'auth0',
    'babel',
    'baidu',
    'behance',
    'bing',
    'bitbucket',
    'bitcoin',
    'blackberry',
    'blogger',
    'bluetooth',
    'bootstrap',
    'buffer',
    'buzzfeed',
    'c',
    'centoos',
    'circleci',
    'clojure',
    'cloudflare',
    'codepen',
    'codesandbox',
    'coffeescript',
    'composer',
    'creativecommons',
    'deviantart',
    'digg',
    'discord',
    'docker',
    'dropbox',
    'drupal',
    'ebay',
    'electron',
    'envato',
    'eslint',
    'ethereum',
    'evernote',
    'facebook',
    'figma',
    'flickr',
    'flipboard',
    'freelancer',
    'gatsby',
    'ghost',
    'git',
    'gitea',
    'github',
    'gitter',
    'gmail',
    'go',
    'google',
    'googlemaps',
    'graphql',
    'gulp',
    'gumroad',
    'gutenberg',
    'helm',
    'heroku',
    'html5',
    'huawei',
    'hubspot',
    'hulu',
    'iconjar',
    'instagram',
    'intel',
    'ios',
    'java',
    'javascript',
    'jekyll',
    'jenkins',
    'joomla',
    'jquery',
    'jsdelivr',
    // 'jsfiddle',
    'json',
    'kubernetes',
    'laravel',
    'letsencrypt',
    'liberapay',
    'linkedin',
    'linux',
    'lua',
    'mailchimp',
    'markdown',
    'mastercard',
    'mediium',
    'meteor',
    'microsoft',
    'microsoftaccess',
    'microsoftazure',
    'microsoftexcel',
    'microsoftoffice',
    'microsoftonedrive',
    'microsoftonenote',
    'microsoftoutlook',
    'microsoftpowerpoint',
    'microsoftteams',
    'microsoftword',
    'mocha',
    'monero',
    'mongodb',
    'mozilla',
    'mysql',
    'nativescript',
    'nginx',
    'node-dot-js',
    'npm',
    'openaccess',
    'openid',
    'opencollective',
    'paypal',
    'php',
    'pinboard',
    'pingdom',
    'pinterest',
    'pocket',
    'postman',
    'powershell',
    'prettier',
    'python',
    'quora',
    'rails',
    'react',
    'reddit',
    'redis',
    'rss',
    'ruby',
    'rust',
    'safari',
    'samsung',
    'samsungpay',
    'sentry',
    'shell',
    'shopify',
    'sinaweibo',
    'sketch',
    'skillshare',
    'skype',
    'slack',
    'snapchat',
    'soundcloud',
    'spotify',
    'stackexchange',
    'stackoverflow',
    'steem',
    'stripe',
    'sublimetext',
    'subversion',
    'swagger',
    'swift',
    // 'symantec',
    'telegram',
    'tensorflow',
    'tesla',
    'tiktok',
    'tor',
    'tumblr',
    'twitter',
    'ubuntu',
    'vim',
    'visa',
    'visualstudio',
    'vk',
    'vue-dot-js',
    'w3c',
    'wechat',
    'whatsapp',
    'wikipedia',
    'windows',
    'wordpress',
    'xbox',
    'xing',
    'yahoo',
    'yammer',
    'yelp',
    'youtube',
    'zoom',
  ]
};

let paths = {
  package: path.join(options.source, 'package.json'),
  svgs: path.join(options.source, 'icons'),
  dest: __dirname,
  svgsDest: path.join(__dirname, 'icons')
};

let info = extraFromJson(paths.package, ['homepage', 'description', 'version', 'author', 'license']);

options.license = info.license;
options.author = info.author.name;
options.homepage = info.homepage;
options.description = info.description;
options.version = info.version;
options.svgs = getSelectedSvgs(getSvgs(paths.svgs), options.selections);

module.exports = function(callback) {
  clean(paths.dest);
  copySvgs(paths.svgsDest, paths.svgs, options.svgs);
  generateFontsFromSvg(paths.dest, options, () => {
    options.icons = getIconsFromCss3(`${__dirname}/${options.name}.css`, 'si-');
    options = prepareIcons(options);
    generateJson(paths.dest, options.className, options);
    copyLicense(paths.dest, path.join(options.source, 'LICENSE.md'));
    jsonfile(paths.dest, options);
    callback();
  });
};
