#!/usr/bin/env node

const argv = require('yargs').argv;
const colors = require('colors');

let importer = require(`../../modules/${argv.module}/importer`);
importer();

console.log(colors.green(`${argv.module} imported.`));